
package packt.jee.eclipse.ws.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CourseManagementServiceService", targetNamespace = "http://soap.ws.eclipse.jee.packt/", wsdlLocation = "http://localhost:8080/CourseMgmtWSProject/courseService?wsdl")
public class CourseManagementServiceService
    extends Service
{

    private final static URL COURSEMANAGEMENTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException COURSEMANAGEMENTSERVICESERVICE_EXCEPTION;
    private final static QName COURSEMANAGEMENTSERVICESERVICE_QNAME = new QName("http://soap.ws.eclipse.jee.packt/", "CourseManagementServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/CourseMgmtWSProject/courseService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COURSEMANAGEMENTSERVICESERVICE_WSDL_LOCATION = url;
        COURSEMANAGEMENTSERVICESERVICE_EXCEPTION = e;
    }

    public CourseManagementServiceService() {
        super(__getWsdlLocation(), COURSEMANAGEMENTSERVICESERVICE_QNAME);
    }

    public CourseManagementServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COURSEMANAGEMENTSERVICESERVICE_QNAME, features);
    }

    public CourseManagementServiceService(URL wsdlLocation) {
        super(wsdlLocation, COURSEMANAGEMENTSERVICESERVICE_QNAME);
    }

    public CourseManagementServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COURSEMANAGEMENTSERVICESERVICE_QNAME, features);
    }

    public CourseManagementServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CourseManagementServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CourseManagementService
     */
    @WebEndpoint(name = "CourseManagementServicePort")
    public CourseManagementService getCourseManagementServicePort() {
        return super.getPort(new QName("http://soap.ws.eclipse.jee.packt/", "CourseManagementServicePort"), CourseManagementService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CourseManagementService
     */
    @WebEndpoint(name = "CourseManagementServicePort")
    public CourseManagementService getCourseManagementServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.ws.eclipse.jee.packt/", "CourseManagementServicePort"), CourseManagementService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COURSEMANAGEMENTSERVICESERVICE_EXCEPTION!= null) {
            throw COURSEMANAGEMENTSERVICESERVICE_EXCEPTION;
        }
        return COURSEMANAGEMENTSERVICESERVICE_WSDL_LOCATION;
    }

}
